=== Ahmad-Esam12398/Attendance-Management-System/Xml/DataValidator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="id">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="status">
		<xs:restriction base="xs:token">
			<xs:pattern value="[ap]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="studentsRecords">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="class" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="students">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="student">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="id" type="id"/>
													<xs:element name="attendanceDates" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="date" type="xs:date"/>
																<xs:element name="status" type="status"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="id"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Ahmad-Esam12398/Attendance-Management-System/Xml/dummyData.xml
<?xml version="1.0" encoding="UTF-8"?>
<studentsRecords xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\ITI\Projects\XML&amp;C#\new repo\mine\Attendance-Management-System\Xml\DataValidator.xsd">
	<class id="1" name="L1">
		<students>
			<student>
				<id>10</id>
				<attendanceDates>
					<date>2024-03-12</date>
					<status>present</status>
				</attendanceDates>
				<attendanceDates>
					<date>2024-04-12</date>
					<status>present</status>
				</attendanceDates>
			</student>
		</students>
		<instructors>
		</instructors>
	</class>
	<class id="2" name="L2">
		<students>
			<student>
				<id>20</id>
				<attendanceDates>
					<date>2024-04-12</date>
					<status>absent</status>
				</attendanceDates>
				<attendanceDates>
					<date>2024-04-15</date>
					<status>present</status>
				</attendanceDates>
			</student>
			<student>
				<id>21</id>
				<attendanceDates>
					<date>2024-04-12</date>
					<status>absent</status>
				</attendanceDates>
				<attendanceDates>
					<date>2024-04-15</date>
					<status>present</status>
				</attendanceDates>
			</student>
		</students>
		<instructors>
		</instructors>
	</class>
</studentsRecords>
