=== Ahmad-Esam12398/Attendance-Management-System/Xml/usersAuthenticationSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
		<xs:simpleType name="id">
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
			</xs:restriction>
		</xs:simpleType>
		<xs:simpleType name="email">
			<xs:restriction base="xs:string">
				<xs:pattern value="[a-zA-Z0-9_][a-zA-Z0-9_.]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
			</xs:restriction>
		</xs:simpleType>
		<xs:simpleType name="password">
			<xs:restriction base="xs:string">
				    <xs:minLength value="8"/>
					<xs:pattern value=".*[a-z].*"/>
					<xs:pattern value=".*[A-Z].*"/>
					<xs:pattern value=".*\d.*"/>
					<xs:pattern value=".*[@$!%*?&amp;].*"/>
			</xs:restriction>
		</xs:simpleType>
		<xs:simpleType name="role">
			<xs:restriction base="xs:token">
				<xs:enumeration value="admin"/>
				<xs:enumeration value="instructor"/>
				<xs:enumeration value="student"/>
			</xs:restriction>
		</xs:simpleType>
	<xs:element name="users">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="user" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="id" type="id"/>
						<xs:element name="email" type="email"/>
						<xs:element name="password" type="password"/>
						<xs:element name="role" type="role"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	</xs:element>
</xs:schema>

=== Ahmad-Esam12398/Attendance-Management-System/Xml/usersAuthentication.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\ITI\Projects\XML&amp;C#\repo\Attendance-C-project\usersAuthenticationSchema.xsd">
	<user>
		<id>1</id>
		<email>ahmad.esam1231998@gmail.com</email>
		<password>12345678</password>
		<role>admin</role>
	</user>
	<user>
		<id>100</id>
		<email>abdo.osama123@gmail.com</email>
		<password>12345678</password>
		<role>instructor</role>
	</user>
</users>
