=== Ahmad-Esam12398/Attendance-Management-System/Attendence system/Attendence System/Xml/ClassesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="id">
		<xs:restriction base="xs:integer">
			<xs:minExclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="name">
		<xs:restriction base="xs:token">
			<xs:pattern value="[a-zA-Z][0-99]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="maxNumber">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="10"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="classes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="class" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="id"/>
							<xs:element name="name" type="name"/>
							<xs:element name="max" type="maxNumber"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="UniqueClassId">
			<xs:selector xpath="class"/>
			<xs:field xpath="id"/>
		</xs:unique>
		<xs:unique name="UniqueClassName">
			<xs:selector xpath="class"/>
			<xs:field xpath="name"/>
		</xs:unique>
	</xs:element>
</xs:schema>

=== Ahmad-Esam12398/Attendance-Management-System/Attendence system/Attendence System/Xml/ClassesTester.xml
<?xml version="1.0" encoding="UTF-8"?>
<classes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ClassesSchema.xsd">
  <class>
    <id>3</id>
    <name>A1</name>
    <max>10</max>
  </class>
  <class>
    <id>5</id>
    <name>U9</name>
    <max>15</max>
  </class>
  <class>
    <id>8</id>
    <name>o1</name>
    <max>12</max>
  </class>
  <class>
    <id>10</id>
    <name>K4</name>
    <max>15</max>
  </class>
  <class>
    <id>11</id>
    <name>Z3</name>
    <max>17</max>
  </class>
  <class>
    <id>12</id>
    <name>T3</name>
    <max>10</max>
  </class>
</classes>
