=== Ahmad-Esam12398/Attendance-Management-System/Attendence system/Attendence System/Xml/usersAuthenticationSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="id">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="name">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z]{2,}"/>
			<xs:pattern value="[a-zA-Z]{2,} [a-zA-Z]{2,}"/>
			<xs:pattern value="[a-zA-Z]{2,} [a-zA-Z]{2,} [a-zA-Z]{2,}"/>
			<xs:pattern value="[a-zA-Z]{2,} [a-zA-Z]{2,} [a-zA-Z]{2,} [a-zA-Z]{2,}"/>
			<xs:pattern value="[a-zA-Z]{2,} [a-zA-Z]{2,} [a-zA-Z]{2,} [a-zA-Z]{2,} [a-zA-Z]{2,}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="email">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9_][a-zA-Z0-9_.]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="phone">
		<xs:restriction base="id">
			<xs:pattern value="01[0125][0-9]{8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="password">
		<xs:restriction base="xs:string">
			<xs:minLength value="8"/>
			<xs:pattern value=".*[a-z].*"/>
			<xs:pattern value=".*[A-Z].*"/>
			<xs:pattern value=".*\d.*"/>
			<xs:pattern value=".*[@$!%*?&amp;].*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="gender">
		<xs:restriction base="xs:string">
			<xs:pattern value="[mf]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="role">
		<xs:restriction base="xs:token">
			<xs:enumeration value="admin"/>
			<xs:enumeration value="instructor"/>
			<xs:enumeration value="student"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="className">
		<xs:restriction base="xs:token">
			<xs:pattern value="[A-Z][1-999]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="status">
		<xs:restriction base="xs:token">
			<xs:enumeration value="absent"/>
			<xs:enumeration value="present"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="users">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="user" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="id"/>
							<xs:element name="name" type="name"/>
							<xs:element name="email" type="email"/>
							<xs:element name="phone" type="phone"/>
							<xs:element name="password" type="password"/>
							<xs:element name="gender" type="gender"/>
							<xs:element name="role" type="role"/>
							<xs:element name="class" minOccurs="0" maxOccurs="unbounded" type="className"/>
							<xs:element name="attendanceDates" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" type="xs:date"/>
										<xs:element name="status" type="status"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="UniqueUserId">
			<xs:selector xpath="user"/>
			<xs:field xpath="id"/>
		</xs:unique>
		<xs:unique name="UniqueEmail">
			<xs:selector xpath="user"/>
			<xs:field xpath="email"/>
		</xs:unique>
	</xs:element>
</xs:schema>

=== Ahmad-Esam12398/Attendance-Management-System/Xml/usersAuthenticationC#.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="usersAuthenticationSchema.xsd">
  <user>
    <id>1</id>
    <name>Ahmed</name>
    <email>ahmad.esam1231998@gmail.com</email>
    <phone>01015328933</phone>
    <password>12345678</password>
    <gender>m</gender>
    <role>instructor</role>
    <class>L1</class>
  </user>
  <user>
    <id>2</id>
    <name>Mohamed</name>
    <email>mohamed.esam1231998@gmail.com</email>
    <phone>01015328930</phone>
    <password>12345678</password>
    <gender>m</gender>
    <role>student</role>
    <class>L1</class>
    <attendanceDates>
      <date>2024-03-12</date>
      <status>present</status>
    </attendanceDates>
    <attendanceDates>
      <date>2024-04-12</date>
      <status>present</status>
    </attendanceDates>
    <attendanceDates>
      <date>2024-02-28</date>
      <status>absent</status>
    </attendanceDates>
    <attendanceDates>
      <date>2024-02-29</date>
      <status>absent</status>
    </attendanceDates>
    <attendanceDates>
      <date>2024-03-01</date>
      <status>absent</status>
    </attendanceDates>
  </user>
  <user>
    <id>3</id>
    <name>Abdo</name>
    <email>abdo.osama123@gmail.com</email>
    <phone>01125488751</phone>
    <password>12345678</password>
    <gender>m</gender>
    <role>admin</role>
  </user>
  <user>
    <id>4</id>
    <name>Habiba</name>
    <email>habiba122@gmail.com</email>
    <phone>01254882366</phone>
    <password>12345678</password>
    <gender>f</gender>
    <role>admin</role>
  </user>
  <user>
    <id>5</id>
    <name>amina</name>
    <email>amina@gmail.com</email>
    <phone>01020228030</phone>
    <password>1234567aa#</password>
    <gender>f</gender>
    <role>student</role>
    <class>R1</class>
    <attendanceDates>
      <date>2024-02-29</date>
      <status>absent</status>
    </attendanceDates>
    <attendanceDates>
      <date>2024-03-01</date>
      <status>absent</status>
    </attendanceDates>
  </user>
  <user>
    <id>6</id>
    <name>ahmed</name>
    <email>ahmedE@gmail.com</email>
    <phone>01020228030</phone>
    <password>123456789aa#</password>
    <gender>m</gender>
    <role>student</role>
    <class>Q1</class>
  </user>
  <user>
    <id>7</id>
    <name>ahmed</name>
    <email>ahmedE1@gmail.com</email>
    <phone>01020228030</phone>
    <password>123456789aa#</password>
    <gender>m</gender>
    <role>student</role>
    <class>C1</class>
  </user>
  <user>
    <id>8</id>
    <name>esraa</name>
    <email>esraa@gmail.com</email>
    <phone>01020228030</phone>
    <password>1234567aa#</password>
    <gender>f</gender>
    <role>student</role>
    <class>Z1</class>
  </user>
  <user>
    <id>9</id>
    <name>soha</name>
    <email>soha@gmail.com</email>
    <phone>01020228030</phone>
    <password>1234567aa#</password>
    <gender>f</gender>
    <role>student</role>
    <class>C1</class>
  </user>
  <user>
    <id>10</id>
    <name>shimaa</name>
    <email>shimaa@gmail.com</email>
    <phone>01020228030</phone>
    <password>1234567aa#</password>
    <gender>f</gender>
    <role>student</role>
    <class>C1</class>
  </user>
  <user>
    <id>11</id>
    <name>nasr</name>
    <email>nasr@gmail.com</email>
    <phone>01020228030</phone>
    <password>1234567aa#</password>
    <gender>f</gender>
    <role>student</role>
    <class>C1</class>
  </user>
</users>

=== Ahmad-Esam12398/Attendance-Management-System/Attendence system/Attendence System/Xml/usersAuthentication.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="usersAuthenticationSchema.xsd">
  <user>
    <id>1</id>
    <name>Ahmed</name>
    <email>ahmad.esam1231998@gmail.com</email>
    <phone>01015328933</phone>
    <password>12345678</password>
    <gender>m</gender>
    <role>instructor</role>
    <class>L1</class>
  </user>
  <user>
    <id>2</id>
    <name>Mohamed</name>
    <email>mohamed.esam1231998@gmail.com</email>
    <phone>01015328930</phone>
    <password>12345678</password>
    <gender>m</gender>
    <role>student</role>
    <class>L1</class>
    <attendanceDates>
      <date>2024-03-12</date>
      <status>present</status>
    </attendanceDates>
    <attendanceDates>
      <date>2024-04-12</date>
      <status>present</status>
    </attendanceDates>
    <attendanceDates>
      <date>2024-03-01</date>
      <status>present</status>
    </attendanceDates>
  </user>
  <user>
    <id>3</id>
    <name>Abdo</name>
    <email>abdo.osama123@gmail.com</email>
    <phone>01125488751</phone>
    <password>12345678</password>
    <gender>m</gender>
    <role>admin</role>
  </user>
  <user>
    <id>4</id>
    <name>Habiba</name>
    <email>habiba122@gmail.com</email>
    <phone>01254882366</phone>
    <password>12345678</password>
    <gender>f</gender>
    <role>admin</role>
  </user>
</users>
